### ISSUE TITLE
Make builder a python package

### ISSUE THREAD

**Issue by Clockwork-Muse** [tobspr/P3DModuleBuilder#16]
The current process is unhandy, because:
 - It requires a clone of the project.
     - once for each module being built, too, which means separation of concerns is hard.
 - It pollutes source control with the cloned files (submodules are not an option, since you can't clone a submodule into a non-empty directory).

Ideally, the module builder could be a pip package that can be installed as normal, then used as a regular command-line tool, ie `build-panda-module <path-to-module-dir>`.  This should be possible, but requires large, breaking, changes to the tool.
(among other things, there's now a `cmake` python package, which could be taken as a dependency).

**Comment by Clockwork-Muse** [comment]
I've done some initial investigation of this, but I'm not very knowledgeable about `cmake` builds.  My current line of thinking is that any such tool is going to have to write a `CMakeLists.txt` to the project directory (if it doesn't exist), potentially also removing the `config.ini` and moving its properties inside the cmake file.

**Comment by Clockwork-Muse** [comment]
There's also the side question of whether there should be some thought toward pulling this or a similar tool into panda itself.  If most cases are rather trivial extensions of panda, or an inclusion of some modern cmake project, it may make it more ergonomic to have panda be pedantic about C++ extension modules.

**Comment by rdb** [comment]
Please note that Panda3D's new CMake build system support provides an easy way to pull in the Panda3D libraries in a user's CMake file.

**Comment by Clockwork-Muse** [comment]
@rdb - but wouldn't that require a local clone (and build) of panda, as opposed to just using the official builds?  Which would run into the same issues as I'm dealing with in #15 on at least some platforms.  The goal here would be trying to reduce the number of different components required.

**Comment by rdb** [comment]
No, we'd ship the necessary FindPanda3D.cmake / Panda3DConfig.cmake scripts with the SDK builds of Panda3D so that user CMake scripts can find it automatically with `find_package(Panda3D)`.

**Comment by Clockwork-Muse** [comment]
Okay, that's more reasonable; although there's still the binary compat issue (which may not be resolvable without consumer infrastructure work anyways...).

**Comment by Clockwork-Muse** [comment]
Even then, the primary benefit of this tool is to make getting a compiled module _trivial_, just a matter of a single python command.  If it doesn't exist, you have to write the cmake files, figure out all the relevant interrogate settings and options, etc.

**Comment by Clockwork-Muse** [comment]
I'm closing this, because this functionality already exists - via at least [scikit-build](https://pypi.org/project/scikit-build/) (and possibly other projects).  When panda itself is moved to cmake, it will only make finding the relevant panda entries easier (and presumably will either contain interrogate targets, or move to a more standard binding library).

Until then, here's a [sample application framework repository](https://github.com/Clockwork-Muse/panda_module_sample) that's based on one I'm using internally.
Note that it needs `pip>=20` for the buildsystem to run, either when installing dependencies for local development, or creation of the built application.
It's not going to completely/correctly compile/run with public assets, because linux application compilation requires it being compiled on a manylinux wheel, and there are no published `.rpm` sdks, but it at least shows the framework of what is required.
